// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using scafoldold.Models;

#nullable disable

namespace scafoldold.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251225085700_CreateUserOrdersTable")]
    partial class CreateUserOrdersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("scafoldold.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("user_orders");
                });

            modelBuilder.Entity("scafoldold.Models.ProjCountry", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("country_Id");

                    b.Property<string>("CountryNames")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("country_names");

                    b.HasKey("CountryId")
                        .HasName("PRIMARY");

                    b.ToTable("proj_country", (string)null);
                });

            modelBuilder.Entity("scafoldold.Models.ProjDistrict", b =>
                {
                    b.Property<int>("DistrictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("district_id");

                    b.Property<string>("DistrictNames")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("district_names");

                    b.Property<int?>("StateId")
                        .HasColumnType("int")
                        .HasColumnName("state_id");

                    b.HasKey("DistrictId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "StateId" }, "state_id");

                    b.ToTable("proj_district", (string)null);
                });

            modelBuilder.Entity("scafoldold.Models.ProjId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("country_id");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int")
                        .HasColumnName("district_id");

                    b.Property<int?>("StateId")
                        .HasColumnType("int")
                        .HasColumnName("state_id");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int")
                        .HasColumnName("users_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CountryId" }, "country_id");

                    b.HasIndex(new[] { "DistrictId" }, "district_id");

                    b.HasIndex(new[] { "StateId" }, "state_id")
                        .HasDatabaseName("state_id1");

                    b.HasIndex(new[] { "UsersId" }, "users_id");

                    b.ToTable("proj_id", (string)null);
                });

            modelBuilder.Entity("scafoldold.Models.ProjState", b =>
                {
                    b.Property<int>("StateId")
                        .HasColumnType("int")
                        .HasColumnName("state_id");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("country_id");

                    b.Property<string>("StateNames")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("state_names");

                    b.HasKey("StateId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CountryId" }, "country_id")
                        .HasDatabaseName("country_id1");

                    b.ToTable("proj_state", (string)null);
                });

            modelBuilder.Entity("scafoldold.Models.ProjDistrict", b =>
                {
                    b.HasOne("scafoldold.Models.ProjState", "State")
                        .WithMany("ProjDistricts")
                        .HasForeignKey("StateId")
                        .HasConstraintName("proj_district_ibfk_1");

                    b.Navigation("State");
                });

            modelBuilder.Entity("scafoldold.Models.ProjId", b =>
                {
                    b.HasOne("scafoldold.Models.ProjCountry", "Country")
                        .WithMany("ProjIds")
                        .HasForeignKey("CountryId")
                        .HasConstraintName("proj_id_ibfk_2");

                    b.HasOne("scafoldold.Models.ProjState", "State")
                        .WithMany("ProjIds")
                        .HasForeignKey("StateId")
                        .HasConstraintName("proj_id_ibfk_3");

                    b.Navigation("Country");

                    b.Navigation("State");
                });

            modelBuilder.Entity("scafoldold.Models.ProjState", b =>
                {
                    b.HasOne("scafoldold.Models.ProjCountry", "Country")
                        .WithMany("ProjStates")
                        .HasForeignKey("CountryId")
                        .HasConstraintName("proj_state_ibfk_1");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("scafoldold.Models.ProjCountry", b =>
                {
                    b.Navigation("ProjIds");

                    b.Navigation("ProjStates");
                });

            modelBuilder.Entity("scafoldold.Models.ProjState", b =>
                {
                    b.Navigation("ProjDistricts");

                    b.Navigation("ProjIds");
                });
#pragma warning restore 612, 618
        }
    }
}
